---
title: GSEAplot - R package

subtitle: Civelek Lab, University of Virginia
author: Sarah Innis, Kelsie Reinaltt, Mete Civelek, Warren Anderson
date: May 23, 2020
output:
  pdf_document:
    toc: true
    toc_depth: 2
  html_document:
    df_print: paged
    toc: true
    
---

\pagebreak

#a
##b
###c

```{r echo=TRUE,results='hide',message=FALSE,warning=FALSE, error=FALSE}
remotes::install_github("kelsiereinaltt/GSEAplot")
library(devtools)
library(GSEAplot)

data(aagmex_expr)
expr.input=aagmex_expr

data(aagmex_pheno)
pheno.input=aagmex_pheno

data(hallmark.gs)
gene.set.input=hallmark.gs


```

```{r warning=FALSE}
start_time <-Sys.time()

 pp= GSEAplots(input.ds.name=expr.input,
               input.cls.name=pheno.input,
               gene.set.input=gene.set.input,
               doc.string="GSEA_plots",
               nperm=1000,
               abs.val=F,
               bar_percent=0.1,
               gap_percent=0.1,
               under_percent=0.1,
               upper_percent=0.1,
               color_line="black",
               color_tick="black")
 
 end_time <- Sys.time()
 end_time-start_time

```

```{r}
sleep_for_a_minute <- function() { Sys.sleep(60) }

start_time <- Sys.time()
sleep_for_a_minute()
end_time <- Sys.time()

end_time - start_time
```



